# Generated by Django 3.1.2 on 2023-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230907_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=56, max_length=100),
            preserve_default=False,
        ),
    ]
